### ISSUE TITLE
Add change tab size (in addition to showing it?)

### ISSUE THREAD

**Issue by ghost** [glebm/render-whitespace-on-github#10]
~This extension doesn't seem to play nice with other extensions that change tab size. Maybe that functionality could be integrated?~ (I didn't refresh the page after installing the tab size changer)

It would be nice to have tabsize and renderability in the same extension. But feel free to close this issue if you feel otherwise.

**Comment by glebm** [comment]
This extension does play nicely with tab size changing extensions.

However, it doesn't update dynamically. You could try implementing it by observing changes ([MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)) to the `style` elements on `body` and `head` (and perhaps changes to the `style` attribute on the relevant nodes). It's a bit tricky but I'll accept a clean implementation.

> It would be nice to have tabsize and renderability in the same extension.

I'd rather not, for separation of concerns.

Examples of how extensions may change tab size dynamically:

* Modifying a `<style>` node attached to `<body>`:
  https://github.com/lukechilds/github-custom-tab-size/blob/master/src/content.js
* Setting the `style.tabSize` attribute directly on the relevant nodes (haven't found an example).

**Comment by ghost** [comment]
@glebm thanks! ya, I forgot to change the issue title after discovering that I just needed to refresh the page for them to play nicely together. It's probably not a big deal to support dynamic refreshing. I'll close the issue.
